##
## NDK Rest configuration file. Lines beginning with # are comments.
##

# Console log level: TRACE, DEBUG, INFO, WARN, ERROR (default: INFO)
# log_level = "INFO" 

[network]
# Bind to this network address (default: "127.0.0.1:7773")
# listen_addr = "127.0.0.1:7773"

[nostr]
relays = ["ws://192.168.7.233:7777"]

[redis]
# Enable redis (default: false)
enabled = false

# Redis endpoint (default: "redis://127.0.0.1")
# endpoint = "redis://127.0.0.1"

# Expiration in secs (default: 60)
expiration = 60
