##
## NDK Rest configuration file. Lines beginning with # are comments.
##

# Console log level: TRACE, DEBUG, INFO, WARN, ERROR (default: INFO)
# log_level = "INFO" 

[network]
# Bind to this network address (default: "127.0.0.1:7773")
# listen_addr = "127.0.0.1:7773"

[nostr]
relays = ["ws://192.168.7.233:7777"]
